spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/audit-test}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:test}

org:
  hibernate:
    envers:
      audit_table_suffix: "_audit"
      audit_strategy: "org.hibernate.envers.strategy.internal.ValidityAuditStrategy"
      autoRegisterListeners: false
